<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsTableSeeder extends Seeder
{
    public function run()
    {
        $permissions = [
            ['id' => 2, 'name' => 'Dashboard', 'group' => 'AdminController', 'code' => 'admin.dashboard'],
            ['id' => 3, 'name' => 'Report Request', 'group' => 'AdminController', 'code' => 'admin.request.report'],
            ['id' => 5, 'name' => 'Download Attachment', 'group' => 'AdminController', 'code' => 'admin.download.attachment'],
            ['id' => 6, 'name' => 'Roles Index', 'group' => 'RolesController', 'code' => 'admin.roles.index'],
            ['id' => 7, 'name' => 'Roles Add', 'group' => 'RolesController', 'code' => 'admin.roles.add'],
            ['id' => 8, 'name' => 'Roles Edit', 'group' => 'RolesController', 'code' => 'admin.roles.edit'],
            ['id' => 9, 'name' => 'Roles Save', 'group' => 'RolesController', 'code' => 'admin.roles.save'],
            ['id' => 10, 'name' => 'All Categories', 'group' => 'CategoryController', 'code' => 'admin.product.category.index'],
            ['id' => 11, 'name' => 'Delete Category', 'group' => 'CategoryController', 'code' => 'admin.product.category.delete'],
            ['id' => 12, 'name' => 'Store Category', 'group' => 'CategoryController', 'code' => 'admin.product.category.store'],
            ['id' => 13, 'name' => 'Import Category', 'group' => 'CategoryController', 'code' => 'admin.product.category.import'],
            ['id' => 14, 'name' => 'All Brands', 'group' => 'BrandController', 'code' => 'admin.product.brand.index'],
            ['id' => 15, 'name' => 'Delete Brand', 'group' => 'BrandController', 'code' => 'admin.product.brand.delete'],
            ['id' => 16, 'name' => 'Store Brand', 'group' => 'BrandController', 'code' => 'admin.product.brand.store'],
            ['id' => 17, 'name' => 'Import Brand', 'group' => 'BrandController', 'code' => 'admin.product.brand.import'],
            ['id' => 18, 'name' => 'All Unit', 'group' => 'UnitController', 'code' => 'admin.product.unit.index'],
            ['id' => 19, 'name' => 'Delete Unit', 'group' => 'UnitController', 'code' => 'admin.product.unit.delete'],
            ['id' => 20, 'name' => 'Store Unit', 'group' => 'UnitController', 'code' => 'admin.product.unit.store'],
            ['id' => 21, 'name' => 'Import Unit', 'group' => 'UnitController', 'code' => 'admin.product.unit.import'],
            ['id' => 22, 'name' => 'All Product', 'group' => 'ProductController', 'code' => 'admin.product.index'],
            ['id' => 23, 'name' => 'Add Product', 'group' => 'ProductController', 'code' => 'admin.product.create'],
            ['id' => 24, 'name' => 'Product Edit', 'group' => 'ProductController', 'code' => 'admin.product.edit'],
            ['id' => 25, 'name' => 'Product Store', 'group' => 'ProductController', 'code' => 'admin.product.store'],
            ['id' => 26, 'name' => 'Product Alert', 'group' => 'ProductController', 'code' => 'admin.product.alert'],
            ['id' => 27, 'name' => 'Product Import', 'group' => 'ProductController', 'code' => 'admin.product.import'],
            ['id' => 28, 'name' => 'All Warehouses', 'group' => 'WarehouseController', 'code' => 'admin.warehouse.index'],
            ['id' => 29, 'name' => 'Store Warehouse', 'group' => 'WarehouseController', 'code' => 'admin.warehouse.store'],
            ['id' => 30, 'name' => 'Import Warehouses', 'group' => 'WarehouseController', 'code' => 'admin.warehouse.import'],
            ['id' => 31, 'name' => 'All Purchases', 'group' => 'PurchaseController', 'code' => 'admin.purchase.index'],
            ['id' => 32, 'name' => 'New Purchase', 'group' => 'PurchaseController', 'code' => 'admin.purchase.new'],
            ['id' => 33, 'name' => 'Edit Purchase', 'group' => 'PurchaseController', 'code' => 'admin.purchase.edit'],
            ['id' => 34, 'name' => 'Store Purchase', 'group' => 'PurchaseController', 'code' => 'admin.purchase.store'],
            ['id' => 35, 'name' => 'Download Purchase PDF', 'group' => 'PurchaseController', 'code' => 'admin.purchase.pdf'],
            ['id' => 36, 'name' => 'Purchase Update', 'group' => 'PurchaseController', 'code' => 'admin.purchase.update'],
            ['id' => 37, 'name' => 'Product Searching', 'group' => 'PurchaseController', 'code' => 'admin.purchase.product.search'],
            ['id' => 38, 'name' => 'Check Purchase Invoice', 'group' => 'PurchaseController', 'code' => 'admin.purchase.invoice.check'],
            ['id' => 39, 'name' => 'Purchase Return', 'group' => 'PurchaseReturnController', 'code' => 'admin.purchase.return.items'],
            ['id' => 40, 'name' => 'All Purchase Return', 'group' => 'PurchaseReturnController', 'code' => 'admin.purchase.return.index'],
            ['id' => 41, 'name' => 'Store Purchase Return', 'group' => 'PurchaseReturnController', 'code' => 'admin.purchase.return.store'],
            ['id' => 42, 'name' => 'Edit Purchase Return', 'group' => 'PurchaseReturnController', 'code' => 'admin.purchase.return.edit'],
            ['id' => 43, 'name' => 'Update Purchase Return', 'group' => 'PurchaseReturnController', 'code' => 'admin.purchase.return.update'],
            ['id' => 44, 'name' => 'Download Purchase Return PDF', 'group' => 'PurchaseReturnController', 'code' => 'admin.purchase.return.pdf'],
            ['id' => 45, 'name' => 'Purchase Return Search Product', 'group' => 'PurchaseReturnController', 'code' => 'admin.purchase.return.search.product'],
            ['id' => 46, 'name' => 'Purchase Return Check Invoice', 'group' => 'PurchaseReturnController', 'code' => 'admin.purchase.return.check.invoice'],
            ['id' => 47, 'name' => 'All Sales', 'group' => 'SaleController', 'code' => 'admin.sale.index'],
            ['id' => 48, 'name' => 'Create Sale', 'group' => 'SaleController', 'code' => 'admin.sale.create'],
            ['id' => 49, 'name' => 'Store Sale', 'group' => 'SaleController', 'code' => 'admin.sale.store'],
            ['id' => 50, 'name' => 'Edit Sale', 'group' => 'SaleController', 'code' => 'admin.sale.edit'],
            ['id' => 51, 'name' => 'Update Sale', 'group' => 'SaleController', 'code' => 'admin.sale.update'],
            ['id' => 52, 'name' => 'Download Sales PDF', 'group' => 'SaleController', 'code' => 'admin.sale.pdf'],
            ['id' => 53, 'name' => 'Sale Search Product', 'group' => 'SaleController', 'code' => 'admin.sale.search.product'],
            ['id' => 54, 'name' => 'Customer Searching', 'group' => 'SaleController', 'code' => 'admin.sale.search.customer'],
            ['id' => 55, 'name' => 'Last Sale Invoice', 'group' => 'SaleController', 'code' => 'admin.sale.last.invoice'],
            ['id' => 56, 'name' => 'All Sales Return', 'group' => 'SaleReturnController', 'code' => 'admin.sale.return.index'],
            ['id' => 57, 'name' => 'Item Of Sale Return', 'group' => 'SaleReturnController', 'code' => 'admin.sale.return.items'],
            ['id' => 58, 'name' => 'Store Sale Return', 'group' => 'SaleReturnController', 'code' => 'admin.sale.return.store'],
            ['id' => 59, 'name' => 'Edit Sale Return', 'group' => 'SaleReturnController', 'code' => 'admin.sale.return.edit'],
            ['id' => 60, 'name' => 'Update Sale Return', 'group' => 'SaleReturnController', 'code' => 'admin.sale.return.update'],
            ['id' => 61, 'name' => 'Download Sale Return PDF', 'group' => 'SaleReturnController', 'code' => 'admin.sale.return.pdf'],
            ['id' => 62, 'name' => 'Sale Return Search Product', 'group' => 'SaleReturnController', 'code' => 'admin.sale.return.search.product'],
            ['id' => 63, 'name' => 'Sale Return Search Customer', 'group' => 'SaleReturnController', 'code' => 'admin.sale.return.search.customer'],
            ['id' => 64, 'name' => 'All Adjustments', 'group' => 'AdjustmentController', 'code' => 'admin.adjustment.index'],
            ['id' => 65, 'name' => 'Create Adjustment', 'group' => 'AdjustmentController', 'code' => 'admin.adjustment.create'],
            ['id' => 66, 'name' => 'Store Adjustment', 'group' => 'AdjustmentController', 'code' => 'admin.adjustment.store'],
            ['id' => 67, 'name' => 'Download Adjustment Details PDF', 'group' => 'AdjustmentController', 'code' => 'admin.adjustment.details.pdf'],
            ['id' => 68, 'name' => 'Edit Adjustment', 'group' => 'AdjustmentController', 'code' => 'admin.adjustment.edit'],
            ['id' => 69, 'name' => 'Update Adjustment', 'group' => 'AdjustmentController', 'code' => 'admin.adjustment.update'],
            ['id' => 70, 'name' => 'Adjustment Product Searching', 'group' => 'AdjustmentController', 'code' => 'admin.adjustment.search.product'],
            ['id' => 71, 'name' => 'All Suppliers', 'group' => 'SupplierController', 'code' => 'admin.supplier.index'],
            ['id' => 72, 'name' => 'Store Supplier', 'group' => 'SupplierController', 'code' => 'admin.supplier.store'],
            ['id' => 73, 'name' => 'Import Suppliers', 'group' => 'SupplierController', 'code' => 'admin.supplier.import'],
            ['id' => 74, 'name' => 'All Customers', 'group' => 'CustomerController', 'code' => 'admin.customer.index'],
            ['id' => 75, 'name' => 'Store Customer', 'group' => 'CustomerController', 'code' => 'admin.customer.store'],
            ['id' => 76, 'name' => 'Import Customers', 'group' => 'CustomerController', 'code' => 'admin.customer.import'],
            ['id' => 77, 'name' => 'Customer Notification Log', 'group' => 'CustomerController', 'code' => 'admin.customer.notification.log'],
            ['id' => 78, 'name' => 'Single Customer Notification', 'group' => 'CustomerController', 'code' => 'admin.customer.notification.single'],
            ['id' => 79, 'name' => 'Customer Notification Single', 'group' => 'CustomerController', 'code' => 'admin.customer.notification.single'],
            ['id' => 80, 'name' => 'Customer All Notification', 'group' => 'CustomerController', 'code' => 'admin.customer.notification.all'],
            ['id' => 81, 'name' => 'Customer Notification Send To All', 'group' => 'CustomerController', 'code' => 'admin.customer.notification.all.send'],
            ['id' => 82, 'name' => 'Customer Email Details', 'group' => 'CustomerController', 'code' => 'admin.customer.email.details'],
            ['id' => 83, 'name' => 'Supplier Payment Index', 'group' => 'SupplierPaymentController', 'code' => 'admin.supplier.payment.index'],
            ['id' => 84, 'name' => 'Supplier Payment Clear', 'group' => 'SupplierPaymentController', 'code' => 'admin.supplier.payment.clear'],
            ['id' => 85, 'name' => 'Store Supplier Payment', 'group' => 'SupplierPaymentController', 'code' => 'admin.supplier.payment.store'],
            ['id' => 86, 'name' => 'Store Supplier Payment Receive', 'group' => 'SupplierPaymentController', 'code' => 'admin.supplier.payment.receive.store'],
            ['id' => 87, 'name' => 'Clear Payment Of Customer', 'group' => 'CustomerPaymentController', 'code' => 'admin.customer.payment.clear'],
            ['id' => 88, 'name' => 'All Customer Payments', 'group' => 'CustomerPaymentController', 'code' => 'admin.customer.payment.index'],
            ['id' => 89, 'name' => 'Store Customer Payment', 'group' => 'CustomerPaymentController', 'code' => 'admin.customer.payment.store'],
            ['id' => 90, 'name' => 'Store Payable Payment Of Customer', 'group' => 'CustomerPaymentController', 'code' => 'admin.customer.payment.payable.store'],
            ['id' => 91, 'name' => 'All Transfers', 'group' => 'TransferController', 'code' => 'admin.transfer.index'],
            ['id' => 92, 'name' => 'Create Transfer', 'group' => 'TransferController', 'code' => 'admin.transfer.create'],
            ['id' => 93, 'name' => 'Edit Transfer', 'group' => 'TransferController', 'code' => 'admin.transfer.edit'],
            ['id' => 94, 'name' => 'Store Transfer', 'group' => 'TransferController', 'code' => 'admin.transfer.store'],
            ['id' => 95, 'name' => 'Download Transfer Pdf', 'group' => 'TransferController', 'code' => 'admin.transfer.pdf'],
            ['id' => 96, 'name' => 'Update Transfer', 'group' => 'TransferController', 'code' => 'admin.transfer.update'],
            ['id' => 97, 'name' => 'Transfer Product Search', 'group' => 'TransferController', 'code' => 'admin.transfer.search.product'],
            // ['id' => 98, 'name' => 'All Expense Types', 'group' => 'ExpenseTypeController', 'code' => 'admin.expense.type.index'],
            ['id' => 98, 'name' => 'All Expense Types', 'group' => 'ExpenseTypeController', 'code' => 'admin.manage_expense_type'],
            ['id' => 99, 'name' => 'Delete Expense Type', 'group' => 'ExpenseTypeController', 'code' => 'admin.expense.type.delete'],
            ['id' => 100, 'name' => 'Store Expense Type', 'group' => 'ExpenseTypeController', 'code' => 'admin.expense.type.store'],
            ['id' => 148, 'name' => 'Download Purchase Return CSV', 'group' => 'PurchaseReturnController', 'code' => 'admin.purchase.return.csv'],
            ['id' => 149, 'name' => 'Download Purchase Return Invoice PDF', 'group' => 'PurchaseReturnController', 'code' => 'admin.purchase.return.invoice.pdf'],
            ['id' => 150, 'name' => 'Download Sales CSV', 'group' => 'SaleController', 'code' => 'admin.sale.csv'],
            ['id' => 151, 'name' => 'Download Sale Invoice PDF', 'group' => 'SaleController', 'code' => 'admin.sale.invoice.pdf'],
            ['id' => 152, 'name' => 'Download Sale Return CSV', 'group' => 'SaleReturnController', 'code' => 'admin.sale.return.csv'],
            ['id' => 153, 'name' => 'Download Sale Return Invoice PDF', 'group' => 'SaleReturnController', 'code' => 'admin.sale.return.invoice.pdf'],
            ['id' => 154, 'name' => 'Download Adjustment PDF', 'group' => 'AdjustmentController', 'code' => 'admin.adjustment.pdf'],
            ['id' => 155, 'name' => 'Download Adjustment CSV', 'group' => 'AdjustmentController', 'code' => 'admin.adjustment.csv'],
            ['id' => 156, 'name' => 'Download Supplier PDF', 'group' => 'SupplierController', 'code' => 'admin.supplier.pdf'],
            ['id' => 157, 'name' => 'Download Supplier CSV', 'group' => 'SupplierController', 'code' => 'admin.supplier.csv'],
            ['id' => 158, 'name' => 'Download Supplier Payment PDF', 'group' => 'SupplierPaymentController', 'code' => 'admin.supplier.payment.pdf'],
            ['id' => 159, 'name' => 'Download Customer Payment Pdf', 'group' => 'CustomerPaymentController', 'code' => 'admin.customer.payment.pdf'],
            ['id' => 160, 'name' => 'Download Transfer CSV', 'group' => 'TransferController', 'code' => 'admin.transfer.csv'],
            ['id' => 161, 'name' => 'Download Transfer Details PDF', 'group' => 'TransferController', 'code' => 'admin.transfer.details.pdf'],
            ['id' => 162, 'name' => 'Download Expense PDF', 'group' => 'ExpenseController', 'code' => 'admin.expense.pdf'],
            ['id' => 163, 'name' => 'Download Expense CSV', 'group' => 'ExpenseController', 'code' => 'admin.expense.csv'],
            ['id' => 164, 'name' => 'Download Supplier Payment Report PDF', 'group' => 'PaymentReportController', 'code' => 'admin.report.payment.supplier.pdf'],
            ['id' => 165, 'name' => 'Download Supplier Payment Report CSV', 'group' => 'PaymentReportController', 'code' => 'admin.report.payment.supplier.csv'],
            ['id' => 166, 'name' => 'Download Customer Payment Report PDF', 'group' => 'PaymentReportController', 'code' => 'admin.report.payment.customer.pdf'],
            ['id' => 167, 'name' => 'Download Customer Payment Report CSV', 'group' => 'PaymentReportController', 'code' => 'admin.report.payment.customer.csv'],
            ['id' => 168, 'name' => 'Stock Report', 'group' => 'StockReportController', 'code' => 'admin.report.stock.index'],
            ['id' => 169, 'name' => 'Stock Report PDF', 'group' => 'StockReportController', 'code' => 'admin.report.stock.pdf'],
            ['id' => 170, 'name' => 'Stock Report CSV', 'group' => 'StockReportController', 'code' => 'admin.report.stock.csv'],
            ['id' => 177, 'name' => 'Notifications', 'group' => 'AdminController', 'code' => 'admin.notifications'],
            ['id' => 178, 'name' => 'Notification Read', 'group' => 'AdminController', 'code' => 'admin.notification.read'],
            ['id' => 179, 'name' => 'Notifications Read All', 'group' => 'AdminController', 'code' => 'admin.notifications.read.all'],
            ['id' => 180, 'name' => 'Notifications Delete All', 'group' => 'AdminController', 'code' => 'admin.notifications.delete.all'],
            ['id' => 181, 'name' => 'Notifications Delete Single', 'group' => 'AdminController', 'code' => 'admin.notifications.delete.single'],
            ['id' => 183, 'name' => 'System Setting', 'group' => 'GeneralSettingController', 'code' => 'admin.setting.system'],
            ['id' => 184, 'name' => 'General Setting', 'group' => 'GeneralSettingController', 'code' => 'admin.setting.general'],
            ['id' => 189, 'name' => 'Sitemap Setting', 'group' => 'GeneralSettingController', 'code' => 'admin.setting.sitemap'],
            ['id' => 191, 'name' => 'Robot Setting', 'group' => 'GeneralSettingController', 'code' => 'admin.setting.robot'],
            ['id' => 193, 'name' => 'Notification Global Email', 'group' => 'NotificationController', 'code' => 'admin.setting.notification.global.email'],
            ['id' => 194, 'name' => 'Notification Global Email Update', 'group' => 'NotificationController', 'code' => 'admin.setting.notification.global.email.update'],
            ['id' => 195, 'name' => 'Notification Global SMS', 'group' => 'NotificationController', 'code' => 'admin.setting.notification.global.sms'],
            ['id' => 196, 'name' => 'Notification Global SMS Update', 'group' => 'NotificationController', 'code' => 'admin.setting.notification.global.sms.update'],
            ['id' => 201, 'name' => 'System Update', 'group' => 'SystemController', 'code' => 'admin.system.update'],
            ['id' => 202, 'name' => 'System Update Process', 'group' => 'SystemController', 'code' => 'admin.system.update.process'],
            ['id' => 203, 'name' => 'System Update Log', 'group' => 'SystemController', 'code' => 'admin.system.update.log'],
            ['id' => 204, 'name' => 'Banned', 'group' => 'AdminController', 'code' => 'admin.banned'],
            ['id' => 205, 'name' => 'Request Report Store', 'group' => 'AdminController', 'code' => 'admin.request.report.store'],
            ['id' => 206, 'name' => 'General Update Setting', 'group' => 'GeneralSettingController', 'code' => 'admin.setting.general.update'],
            ['id' => 207, 'name' => 'System Configuration Update Setting', 'group' => 'GeneralSettingController', 'code' => 'admin.setting.system.configuration.update'],
            ['id' => 208, 'name' => 'Notification Email Update', 'group' => 'NotificationController', 'code' => 'admin.setting.notification.email.update'],
            ['id' => 209, 'name' => 'Setting Notification SMS Update', 'group' => 'NotificationController', 'code' => 'admin.setting.notification.sms.update'],
            ['id' => 210, 'name' => 'Sitemap Update Setting', 'group' => 'GeneralSettingController', 'code' => 'admin.setting.sitemap.update'],
            ['id' => 211, 'name' => 'Robot Update Setting', 'group' => 'GeneralSettingController', 'code' => 'admin.setting.robot.update'],
            ['id' => 212, 'name' => 'Warehouse Status', 'group' => 'WarehouseController', 'code' => 'admin.warehouse.status'],
            ['id' => 213, 'name' => 'Customer List', 'group' => 'CustomerController', 'code' => 'admin.customer.list'],
            ['id' => 214, 'name' => 'Customer Segment Count', 'group' => 'CustomerController', 'code' => 'admin.customer.segment.count'],
            ['id' => 215, 'name' => 'Customer Notification History', 'group' => 'CustomerController', 'code' => 'admin.customer.notification.history'],
            ['id' => 216, 'name' => 'Extensions Index', 'group' => 'ExtensionController', 'code' => 'admin.extensions.index'],
            ['id' => 217, 'name' => 'Extensions Update', 'group' => 'ExtensionController', 'code' => 'admin.extensions.update'],
            ['id' => 218, 'name' => 'Extensions Status', 'group' => 'ExtensionController', 'code' => 'admin.extensions.status'],
            ['id' => 219, 'name' => 'Chart Purchase Sale', 'group' => 'AdminController', 'code' => 'admin.chart.purchase.sale'],
            ['id' => 220, 'name' => 'Chart Sales Return', 'group' => 'AdminController', 'code' => 'admin.chart.sales.return'],
            ['id' => 221, 'name' => 'Chart Purchases Return', 'group' => 'AdminController', 'code' => 'admin.chart.purchases.return'],
            ['id' => 222, 'name' => 'Service Stock Detail', 'group' => 'ServiceStockController', 'code' => 'admin.manage_stock_details'],
            ['id' => 223, 'name' => 'Service Stock In', 'group' => 'ServiceStockController', 'code' => 'admin.manage_stock_in'],
            ['id' => 224, 'name' => 'Service Stock Out', 'group' => 'ServiceStockController', 'code' => 'admin.manage_stock_out'],
            ['id' => 225, 'name' => 'Service Stock Transfer', 'group' => 'ServiceStockController', 'code' => 'admin.manage_stock_transfer'],
            ['id' => 226, 'name' => 'Service Stock Report', 'group' => 'ServiceStockController', 'code' => 'admin.stock_client_details'],
            ['id' => 227, 'name' => 'Service Stock Payment', 'group' => 'ServiceStockController', 'code' => 'admin.stock_client_payment'],
            ['id' => 228, 'name' => 'Day Book', 'group' => 'DayBookController', 'code' => 'admin.daybook.index'],
            ['id' => 229, 'name' => 'Manufacturing Unit', 'group' => 'ManufacturingUnitController', 'code' => 'admin.production_flow'],
            ['id' => 230, 'name' => 'Manage Expenses', 'group' => 'ExpenseTypeController', 'code' => 'admin.manage_expense'],
            ['id' => 231, 'name' => 'Banks Management', 'group' => 'BanksManagementController', 'code' => 'admin.bank.index'],
            ['id' => 232, 'name' => 'Service Stock Edit', 'group' => 'ServiceStockController', 'code' => 'admin.manage_stock_in.edit'],


        ];

        foreach ($permissions as $permission) {
            DB::table('permissions')->updateOrInsert(
                ['id' => $permission['id']],
                $permission
            );
        }
    }
}
